### ISSUE TITLE
Add README files for sub directories

### ISSUE THREAD

**Issue by maluramichael** [Devnetik/react-native-skeleton#3]
Create readme files for directories like app/routes or app/api so it is easier to document this special contexts.

**Comment by danielksan81** [comment]
Hi, as the app/routes is existent, I can add a proper Readme there and add a link from the root Readme if wanted. The app/api folder is not existent, should it be created?

**Comment by maluramichael** [comment]
app/routes would be nice. I moved the app/api folder to app/core/api.
